# Data Slicing with NumPy

In [1]:
#import packages 
import numpy as np

In [3]:
#Create 1D ndarray 
#We will the arrange method to create our data 
myData = np.arange(0, 10000, 99)
print(myData)

[   0   99  198  297  396  495  594  693  792  891  990 1089 1188 1287
 1386 1485 1584 1683 1782 1881 1980 2079 2178 2277 2376 2475 2574 2673
 2772 2871 2970 3069 3168 3267 3366 3465 3564 3663 3762 3861 3960 4059
 4158 4257 4356 4455 4554 4653 4752 4851 4950 5049 5148 5247 5346 5445
 5544 5643 5742 5841 5940 6039 6138 6237 6336 6435 6534 6633 6732 6831
 6930 7029 7128 7227 7326 7425 7524 7623 7722 7821 7920 8019 8118 8217
 8316 8415 8514 8613 8712 8811 8910 9009 9108 9207 9306 9405 9504 9603
 9702 9801 9900 9999]


In [5]:
myData.size

102

In [7]:
#Basic slice 
#list the first five entries in our ndarray 
mySlice= myData[0:5]
mySlice
#Note this will not include the final entry 

array([  0,  99, 198, 297, 396])

In [8]:
#If we leave the end point black it will default to 0 
mySlice_2 = myData[:5]
mySlice_2

array([  0,  99, 198, 297, 396])

In [9]:
#If we the end point empty it will default to n 
mySlice_2= myData[97:]
mySlice_2

array([9603, 9702, 9801, 9900, 9999])

In [10]:
#Let's do an example with the step 
mySlice_2=myData[::10]
mySlice_2

array([   0,  990, 1980, 2970, 3960, 4950, 5940, 6930, 7920, 8910, 9900])

# Slicing with NumPy 

Now lets mess around with some real data that is hosted online.

In [12]:
#Here we are just importing some data to work with and setting it up as a ndarray (we will go over the ins and outs a little late ). There are 573 data points 
import pandas as pd
salariesdf = pd.read_csv('https://gitlab.com/CEADS/DrKerby/python/raw/master/NBA_season1718_salary.csv')
salaries = salariesdf['season17_18'].values
salaries


array([3.4682550e+07, 3.3285709e+07, 3.1269231e+07, 2.9727900e+07,
       2.9512900e+07, 2.8703704e+07, 2.8530608e+07, 2.8530608e+07,
       2.8299399e+07, 2.7739975e+07, 2.7734405e+07, 2.6243760e+07,
       2.6153057e+07, 2.5686667e+07, 2.5289390e+07, 2.5000000e+07,
       2.4773250e+07, 2.4599495e+07, 2.3962573e+07, 2.3775506e+07,
       2.3775506e+07, 2.3775506e+07, 2.3775506e+07, 2.3500000e+07,
       2.3112004e+07, 2.3112004e+07, 2.3000000e+07, 2.2642350e+07,
       2.2642350e+07, 2.2642350e+07, 2.2642350e+07, 2.2471910e+07,
       2.2471910e+07, 2.2434783e+07, 2.1974719e+07, 2.1461010e+07,
       2.1000000e+07, 2.0566802e+07, 2.0559599e+07, 2.0061729e+07,
       2.0000000e+07, 1.9578455e+07, 1.9508958e+07, 1.9332500e+07,
       1.9301070e+07, 1.9000000e+07, 1.8868625e+07, 1.8868625e+07,
       1.8063850e+07, 1.8063850e+07, 1.7884176e+07, 1.7884176e+07,
       1.7826150e+07, 1.7765000e+07, 1.7745894e+07, 1.7190000e+07,
       1.7131148e+07, 1.7000450e+07, 1.7000000e+07, 1.7000000e

In [13]:
type(salaries)

numpy.ndarray

In [14]:
#We can check the number of entries using len() just like we would with a Python List 
len(salaries)

573

In [17]:
#Lets sort our data 
salaries.sort(kind="mergesort")
salaries 


array([1.7224000e+04, 2.2248000e+04, 2.5000000e+04, 2.5000000e+04,
       2.5000000e+04, 2.5000000e+04, 2.6773000e+04, 4.6080000e+04,
       4.6080000e+04, 4.6080000e+04, 4.6080000e+04, 4.6080000e+04,
       4.6080000e+04, 4.6080000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.0000000e+04, 5.0000000e+04, 5.0000000e+04, 5.0000000e+04,
       5.3465000e+04, 7.4159000e+04, 7.4159000e+04, 7.4159000e+04,
       7.4159000e+04, 8.3129000e+04, 8.3129000e+04, 8.3129000e+04,
       8.7552000e+04, 9.2160000e+04, 9.2160000e+04, 9.2160000e+04,
       9.2160000e+04, 9.2160000e+04, 9.2160000e+04, 9.2160000e+04,
       9.2858000e+04, 1.0000000e+05, 1.0000000e+05, 1.0000000e

In [26]:
#If we place a negative number as our index, numpy will just revert back to the end of the array 
print(salaries[-1])
print(salaries[-2])

34682550.0
33285709.0


In [22]:
#Let's print out the first 10 salaries from our datset 
print(salaries[0:10])

[17224. 22248. 25000. 25000. 25000. 25000. 26773. 46080. 46080. 46080.]


In [27]:
print(salaries[-10:])

[27739975. 28299399. 28530608. 28530608. 28703704. 29512900. 29727900.
 31269231. 33285709. 34682550.]


In [29]:
#If our array isn't sorted and we don't want to sort we can find the max using .max()
#NumPy Method 
salaries.max()
#Python function 
max(salaries)

34682550.0

In [31]:
#We can do min the same way 
#NumPy Method 
salaries.min()
#Python function 
min(salaries)

17224.0

In [32]:
#We can do basic math functions with numpy 
salaries.sum()

3357175993.0

In [34]:
#We use slices with most methods 
#we can add up the last 10 entries in the array 
salaries[-10:].sum()

300282584.0

In [42]:
#We can peform basic math on the entire array 
#Divide all entries our by one million 
salaries_in_million=salaries/1000000
print(salaries_in_million)

[1.7224000e-02 2.2248000e-02 2.5000000e-02 2.5000000e-02 2.5000000e-02
 2.5000000e-02 2.6773000e-02 4.6080000e-02 4.6080000e-02 4.6080000e-02
 4.6080000e-02 4.6080000e-02 4.6080000e-02 4.6080000e-02 5.0000000e-02
 5.0000000e-02 5.0000000e-02 5.0000000e-02 5.0000000e-02 5.0000000e-02
 5.0000000e-02 5.0000000e-02 5.0000000e-02 5.0000000e-02 5.0000000e-02
 5.0000000e-02 5.0000000e-02 5.0000000e-02 5.0000000e-02 5.0000000e-02
 5.0000000e-02 5.0000000e-02 5.0000000e-02 5.0000000e-02 5.0000000e-02
 5.0000000e-02 5.0000000e-02 5.0000000e-02 5.0000000e-02 5.0000000e-02
 5.3465000e-02 7.4159000e-02 7.4159000e-02 7.4159000e-02 7.4159000e-02
 8.3129000e-02 8.3129000e-02 8.3129000e-02 8.7552000e-02 9.2160000e-02
 9.2160000e-02 9.2160000e-02 9.2160000e-02 9.2160000e-02 9.2160000e-02
 9.2160000e-02 9.2858000e-02 1.0000000e-01 1.0000000e-01 1.0000000e-01
 1.0000000e-01 1.0405900e-01 1.1901000e-01 1.1960200e-01 1.4090200e-01
 1.4831800e-01 1.4831800e-01 1.6625800e-01 1.7223800e-01 1.7223800e-01
 1.725

In [40]:
#We can calculate basic stats as well 
print(salaries.mean())
print(np.median(salaries))

5858945.886561954
2386864.0
