# Python List 

Creating a simple Python list

In [ ]:
#Method one: using the []
myList=[] #simple empty list 


In [ ]:
#We can also create a list using the list constructor 
myList_2=list()

Let's add some contents to our list 

In [ ]:
#We can intialize our list with the data already
mylist=[0,1,2,3]
#or 
myList_2=list((0,1,2,3))#note we need to sets or parenthese with the contructor 

We can access the data on a list just by specifying the number of the element we want in the list (as long as it exist)

In [ ]:
print(mylist[0])
print(myList_2[3])

0
3


Python list can contain different data types including other list 

In [ ]:
mylist[3]= "String"
print(mylist)#note we can print the entire list or a specified element 
mylist[3]= 3

[0, 1, 2, 'String']


# Common Methods/Functions for List 

In [ ]:
#The size or length of a list 
len(mylist)

4

In [ ]:
#Make a copy of the list
myNewList=mylist.copy() 
print(myNewList)
myNewList[0]=1
#Note .copy() makes a deep copy
print(myNewList)
print(mylist)

[0, 1, 2, 3]
[1, 1, 2, 3]
[0, 1, 2, 3]


In [ ]:
#count the number of a given value in the list 
mylist.count(2)

1

In [ ]:
#Add an element to the end of the list 
print("Orginal Length")
print(len(mylist))
mylist.append(2)
print("New Length")
print(len(mylist))
#Remenber that the notebook will update all your variables so keep an eye when you change varaible values 

Orginal Length
4
New Length
5


In [ ]:
#Add/remove a value at a given index 
mylist.insert(0,77)
print(mylist)
mylist.remove(0)
print(mylist)

[77, 0, 1, 2, 3, 2]
[77, 1, 2, 3, 2]


In [ ]:
#Reverse a list 
mylist.reverse()
print(mylist)

[2, 3, 2, 1, 77]


In [ ]:
#Sort 
#mylist.sort()#note that you can only sort with values that makes sense 

mylist.sort()#note that you can only sort with values that makes sense 
print(mylist)


[1, 2, 2, 3, 77]


#Pyton Sets, Tuples and Dictionaries 

In [ ]:
#Declare a set 
mySet={2,2,3,4}
print(mySet)#Note no duplicates 

{2, 3, 4}


In [ ]:
#Declare Tuple 
myTuple =("Apple", "Pear", "Banna" )
print(myTuple)

('Apple', 'Pear', 'Banna')


In [ ]:
#Declare Dictionary 
myDictionary = { "A" : 10, "B" : 6, "C": 4, "D" : 0}#Note duplicates are not allowed 
print(myDictionary)

{'A': 10, 'B': 6, 'C': 4, 'D': 0}


In [ ]:
#We can find the size of a dictionary the same way as a list 
print(len(myDictionary))

4


In [ ]:
#Since a dictionary is now ordered we can access the value by key 
print(myDictionary["A"])
# we can update the value the same way
myDictionary["B"]=myDictionary["B"]+1
print(myDictionary["B"])

10
7


# NumPy


In [ ]:
#Import the NumPy Package 
import numpy as np #NumPy is traditionally abbrivated as np for ease of use 

In [ ]:
#Create a 0D numpy array 
myNpArray=np.array(0)
print(myNpArray)

0


In [ ]:
#Create a simple 1D numpy arrray
myNpArray=np.array([5.5,6.7,8.8,9.9])
print(myNpArray)

[5.5 6.7 8.8 9.9]


In [ ]:
#Create a  2D numpy arrray
myNpArray=np.array([[5.5,6.7,8.8,9.9], [1.0,2.0,3.0,4.0]])
print(myNpArray)
#Create a 3D numpy array 
myNpArray=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(myNpArray)

[[5.5 6.7 8.8 9.9]
 [1.  2.  3.  4. ]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#Check the shape of the array
myNpArray.shape


(2, 2, 3)

In [ ]:
#Check the size of the array 
myNpArray.size

12

In [ ]:
#We can easily create random arrays of any size using the .empty method 
myNewNpArray=np.empty((5,5))
print(myNewNpArray)
# we could also use  .zeros 
myNewNpArray=np.zeros((5,5))
print(myNewNpArray)
#or we can make an array of ones if that better suits our needs
myNewNpArray=np.ones((5,5))
print(myNewNpArray)

[[2.41351779e-316 2.47032823e-323 2.41216010e-316 0.00000000e+000
  0.00000000e+000]
 [2.41216959e-316 0.00000000e+000 0.00000000e+000 2.41222176e-316
  0.00000000e+000]
 [0.00000000e+000 2.41214113e-316 0.00000000e+000 0.00000000e+000
  2.41216485e-316]
 [0.00000000e+000 0.00000000e+000 1.11789341e+253 6.01347002e-154
  6.01347002e-154]
 [6.01347002e-154 1.72092739e+088 5.27154974e+246 1.06025488e-153
  8.23610868e+151]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
